MiHadaMadrinaShop/Models/FormasDePago.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;

namespace MiHadaMadrinaShop.Models
{
    public partial class FormasDePago
    {
        public FormasDePago()
        {
            Pedidos = new HashSet<Pedido>();
        }

        public byte IdFormaDePago { get; set; }

        [Display(Name = "Forma de pago")]
        public string FormaDePago { get; set; } = null!;

        public virtual ICollection<Pedido> Pedidos { get; set; }
    }
}

MiHadaMadrinaShop/Areas/Admin/Controllers/FormasDePagos/FormasDePagosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MiHadaMadrinaShop.Models;

namespace MiHadaMadrinaShop.Areas.Admin.Controllers.FormasDePagos
{
    [Area("Admin")]
    public class FormasDePagosController : Controller
    {
        private readonly MiHadaMadrinaHandMadeDBContext _context;

        public FormasDePagosController(MiHadaMadrinaHandMadeDBContext context)
        {
            _context = context;
        }

        // GET: Admin/FormasDePagoes
        public async Task<IActionResult> Index()
        {
            return _context.FormasDePagos != null ?
                        View(await _context.FormasDePagos.ToListAsync()) :
                        Problem("Entity set 'MiHadaMadrinaHandMadeDBContext.FormasDePagos'  is null.");
        }

        // GET: Admin/FormasDePagoes/Details/5
        public async Task<IActionResult> Details(byte? id)
        {
            if (id == null || _context.FormasDePagos == null)
            {
                return NotFound();
            }

            var formasDePago = await _context.FormasDePagos
                .FirstOrDefaultAsync(m => m.IdFormaDePago == id);
            if (formasDePago == null)
            {
                return NotFound();
            }

            return View(formasDePago);
        }

        // GET: Admin/FormasDePagoes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/FormasDePagoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdFormaDePago,FormaDePago")] FormasDePago formasDePago)
        {
            if (ModelState.IsValid)
            {
                _context.Add(formasDePago);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(formasDePago);
        }

        // GET: Admin/FormasDePagoes/Edit/5
        public async Task<IActionResult> Edit(byte? id)
        {
            if (id == null || _context.FormasDePagos == null)
            {
                return NotFound();
            }

            var formasDePago = await _context.FormasDePagos.FindAsync(id);
            if (formasDePago == null)
            {
                return NotFound();
            }
            return View(formasDePago);
        }

        // POST: Admin/FormasDePagoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(byte id, [Bind("IdFormaDePago,FormaDePago")] FormasDePago formasDePago)
        {
            if (id != formasDePago.IdFormaDePago)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(formasDePago);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FormasDePagoExists(formasDePago.IdFormaDePago))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(formasDePago);
        }

        // GET: Admin/FormasDePagoes/Delete/5
        public async Task<IActionResult> Delete(byte? id)
        {
            if (id == null || _context.FormasDePagos == null)
            {
                return NotFound();
            }

            var formasDePago = await _context.FormasDePagos
                .FirstOrDefaultAsync(m => m.IdFormaDePago == id);
            if (formasDePago == null)
            {
                return NotFound();
            }

            return View(formasDePago);
        }

        // POST: Admin/FormasDePagoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(byte id)
        {
            if (_context.FormasDePagos == null)
            {
                return Problem("Entity set 'MiHadaMadrinaHandMadeDBContext.FormasDePagos'  is null.");
            }
            var formasDePago = await _context.FormasDePagos.FindAsync(id);
            if (formasDePago != null)
            {
                _context.FormasDePagos.Remove(formasDePago);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FormasDePagoExists(byte id)
        {
            return (_context.FormasDePagos?.Any(e => e.IdFormaDePago == id)).GetValueOrDefault();
        }
    }
}

MiHadaMadrinaShop/Areas/Admin/Views/FormasDePagos/Create.cshtml
@model MiHadaMadrinaShop.Models.FormasDePago

@{
    ViewData["Title"] = "Crear forma de pago";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="container py-5 d-flex flex-column min-vh-100">
    <div class="row">
        <div class="col mt-4">
            <h1 class="font-weight-bold font-italic">Forma de pago</h1>
        </div>
    </div>
    <ol class="breadcrumb mb-4 bg-transparent">
        <li><a asp-area="Admin" asp-controller="Pedidos" asp-action="Index" class="text-black-50 text-decoration-none">Dashboard</a><i class="fas fa-angle-right text-black-50 px-2"></i></li>
        <li><a asp-area="Admin" asp-controller="FormasDePagos" asp-action="Index" class="text-black-50 text-decoration-none">Forma de pago</a><i class="fas fa-angle-right text-black-50 px-2"></i></li>
        <li><a asp-area="Admin" asp-controller="FormasDePagos" asp-action="Create" class="text-dark text-decoration-none active">Crear</a></li>
    </ol>
    <hr class="d-block d-md-none" />

    <div class="row">
        <div class="col-12 col-md-6 align-items-center">
            <div class="card d-flex justify-content-center p-4">
                <div class="card-header">
                    <h1 class="font-weight-bold font-italic">Crear forma de pago</h1>
                </div>
                <form asp-action="Create" method="post">
                    <div class="card-body py-0">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group mb-3">
                            <label asp-for="FormaDePago" class="control-label"></label>
                            <input asp-for="FormaDePago" class="form-control" />
                            <span asp-validation-for="FormaDePago" class="text-danger"></span>
                        </div>
                        <div class="card-footer">
                            <div class="form-group justify-content-between" role="group" aria-label="Botones">
                                <a asp-action="Index" class="btn btn-secondary w-auto mb-1"><i class="fas fa-arrow-left"></i> Volver</a>&nbsp;
                                <button type="submit" class="btn btn-primary w-auto mb-1"><i class="fas fa-save"></i> Guardar</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="col-8 col-md-4 align-items-center">
            <img src="~/img/illustrations/undraw_my_documents_re_13dc.svg" alt="imagen de creaci&oacute;n" class="imagen-width img-fluid rounded mx-auto" />
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

MiHadaMadrinaShop/Areas/Admin/Views/FormasDePagos/Delete.cshtml
@model MiHadaMadrinaShop.Models.FormasDePago

@{
    ViewData["Title"] = "Eliminar forma de pago";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="container py-5 d-flex flex-column min-vh-100">
    <div class="row">
        <div class="col mt-4">
            <h1 class="font-weight-bold font-italic">Forma de pago</h1>
        </div>
    </div>
    <ol class="breadcrumb mb-4 bg-transparent">
        <li><a asp-area="Admin" asp-controller="Pedidos" asp-action="Index" class="text-black-50 text-decoration-none">Dashboard</a><i class="fas fa-angle-right text-black-50 px-2"></i></li>
        <li><a asp-area="Admin" asp-controller="FormasDePagos" asp-action="Index" class="text-black-50 text-decoration-none">Forma de pago</a><i class="fas fa-angle-right text-black-50 px-2"></i></li>
        <li><a asp-area="Admin" asp-controller="FormasDePagos" asp-action="Delete" class="text-dark text-decoration-none active">Eliminar</a></li>
    </ol>
    <hr class="d-block d-md-none" />

    <div class="row">
        <div class="col-12 col-md-6 align-items-center">
            <div class="card d-flex justify-content-center p-4">
                <div class="card-header">
                    <h1 class="font-weight-bold font-italic">Eliminar forma de pago</h1>
                </div>
                <form asp-action="Delete" method="post">
                    <div class="card-body py-0">
                        <h3>¿Est&aacute;s seguro de querer eliminar la forma de pago @Html.DisplayFor(model => model.FormaDePago)?</h3>
                        <input type="hidden" asp-for="IdFormaDePago" />
                        <div class="card-footer">
                            <div class="form-group justify-content-between" role="group" aria-label="Botones">
                                <a asp-action="Index" class="btn btn-secondary w-auto mb-1"><i class="fas fa-arrow-left"></i> Volver</a>&nbsp;
                                <button type="submit" class="btn btn-danger w-auto mb-1"><i class="fas fa-trash-alt"></i> Eliminar</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="col-8 col-md-4 align-items-center">
            <img src="~/img/illustrations/undraw_cancel_re_pkdm.svg" alt="eliminar imagen" class="imagen-width img-fluid rounded mx-auto" />
        </div>
    </div>
</div>

MiHadaMadrinaShop/Areas/Admin/Views/FormasDePagos/Edit.cshtml
@model MiHadaMadrinaShop.Models.FormasDePago

@{
    ViewData["Title"] = "Edit forma de pago";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="container py-5 d-flex flex-column min-vh-100">
    <div class="row">
        <div class="col mt-4">
            <h1 class="font-weight-bold font-italic">Forma de pago</h1>
        </div>
    </div>
    <ol class="breadcrumb mb-4 bg-transparent">
        <li><a asp-area="Admin" asp-controller="Pedidos" asp-action="Index" class="text-black-50 text-decoration-none">Dashboard</a><i class="fas fa-angle-right text-black-50 px-2"></i></li>
        <li><a asp-area="Admin" asp-controller="FormasDePagos" asp-action="Index" class="text-black-50 text-decoration-none">Forma de pago</a><i class="fas fa-angle-right text-black-50 px-2"></i></li>
        <li><a asp-area="Admin" asp-controller="FormasDePagos" asp-action="Edit" class="text-dark text-decoration-none active">Editar</a></li>
    </ol>
    <hr class="d-block d-md-none" />

    <div class="row">
        <div class="col-12 col-md-6 align-items-center">
            <div class="card d-flex justify-content-center p-4">
                <div class="card-header">
                    <h1 class="font-weight-bold font-italic">Editar forma de pago</h1>
                </div>
                <form asp-action="Edit" method="post">
                    <div class="card-body py-0">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <input type="hidden" asp-for="IdFormaDePago" />
                        <div class="form-group mb-3">
                            <label asp-for="FormaDePago" class="control-label"></label>
                            <input asp-for="FormaDePago" class="form-control" />
                            <span asp-validation-for="FormaDePago" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="form-group justify-content-between" role="group" aria-label="Botones">
                            <a asp-action="Index" class="btn btn-secondary w-auto mb-1"><i class="fas fa-arrow-left"></i> Volver</a>&nbsp;
                            <button type="submit" class="btn btn-primary w-auto mb-1"><i class="fas fa-save"></i> Guardar</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="col-8 col-md-4 align-items-center">
            <img src="~/img/illustrations/undraw_my_documents_re_13dc.svg" alt="imagen de edici&oacute;n" class="imagen-width img-fluid rounded mx-auto" />
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

MiHadaMadrinaShop/Areas/Admin/Views/FormasDePagos/Index.cshtml
@model IEnumerable<MiHadaMadrinaShop.Models.FormasDePago>

@{
    ViewData["Title"] = "Lista de formas de pago";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="container py-5 d-flex flex-column min-vh-100">
    <ol class="breadcrumb mt-4 bg-transparent">
        <li><a asp-area="Admin" asp-controller="Pedidos" asp-action="Index" class="text-black-50 text-decoration-none">Dashboard</a><i class="fas fa-angle-right text-black-50 px-2"></i></li>
        <li><a asp-area="Admin" asp-controller="FormasDePagos" asp-action="Index" class="text-dark text-decoration-none active">Forma de pago</a></li>
    </ol>
    <hr class="d-block d-md-none" />
    <div class="row">
        <div class="col mt-4 d-flex justify-content-between align-items-center">
            <h1 class="font-weight-bold font-italic">Lista de formas de pago</h1>
            <a class="btn btn-primary" asp-action="Create">
                <i class="fas fa-plus"></i><span>&nbsp;Nuevo</span>
            </a>
        </div>
    </div>

    <div class="row">
        <div class="col-12 text-center">
            <div class="table-responsive">
                <table class="table table-hover border">
                    <thead class="thead-color">
                        <tr class="align-self-center">
                            <th class="py-3 text-center" scope="col">
                                @Html.DisplayNameFor(model => model.FormaDePago)
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td class="pt-3 text-center">
                                    @Html.DisplayFor(modelItem => item.FormaDePago)
                                </td>
                                <td class="pt-3 text-center">
                                    <a class="btn btn-warning mx-auto opacity-50" asp-action="Edit" asp-route-id="@item.IdFormaDePago"><i class="fas fa-edit"></i></a>
                                    <a class="btn btn-danger mx-auto" asp-action="Delete" asp-route-id="@item.IdFormaDePago"><i class="fas fa-trash"></i></a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>