MiHadaMadrinaShop/Models/Sexo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;

namespace MiHadaMadrinaShop.Models
{
    public partial class Sexo
    {
        public Sexo()
        {
            AspNetUsers = new HashSet<AspNetUser>();
        }

        public byte IdSexo { get; set; }

        [Display(Name = "Sexo")]
        public string Sexo1 { get; set; } = null!;

        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
    }
}

MiHadaMadrinaShop/Areas/Admin/Controllers/Sexos/SexosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MiHadaMadrinaShop.Models;

namespace MiHadaMadrinaShop.Areas.Admin.Controllers.Sexos
{
    [Area("Admin")]
    public class SexosController : Controller
    {
        private readonly MiHadaMadrinaHandMadeDBContext _context;

        public SexosController(MiHadaMadrinaHandMadeDBContext context)
        {
            _context = context;
        }

        // GET: Admin/Sexos
        public async Task<IActionResult> Index()
        {
              return _context.Sexos != null ? 
                          View(await _context.Sexos.ToListAsync()) :
                          Problem("Entity set 'MiHadaMadrinaHandMadeDBContext.Sexos'  is null.");
        }

        // GET: Admin/Sexos/Details/5
        public async Task<IActionResult> Details(byte? id)
        {
            if (id == null || _context.Sexos == null)
            {
                return NotFound();
            }

            var sexo = await _context.Sexos
                .FirstOrDefaultAsync(m => m.IdSexo == id);
            if (sexo == null)
            {
                return NotFound();
            }

            return View(sexo);
        }

        // GET: Admin/Sexos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/Sexos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdSexo,Sexo1")] Sexo sexo)
        {
            if (ModelState.IsValid)
            {
                _context.Add(sexo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(sexo);
        }

        // GET: Admin/Sexos/Edit/5
        public async Task<IActionResult> Edit(byte? id)
        {
            if (id == null || _context.Sexos == null)
            {
                return NotFound();
            }

            var sexo = await _context.Sexos.FindAsync(id);
            if (sexo == null)
            {
                return NotFound();
            }
            return View(sexo);
        }

        // POST: Admin/Sexos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(byte id, [Bind("IdSexo,Sexo1")] Sexo sexo)
        {
            if (id != sexo.IdSexo)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(sexo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SexoExists(sexo.IdSexo))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(sexo);
        }

        // GET: Admin/Sexos/Delete/5
        public async Task<IActionResult> Delete(byte? id)
        {
            if (id == null || _context.Sexos == null)
            {
                return NotFound();
            }

            var sexo = await _context.Sexos
                .FirstOrDefaultAsync(m => m.IdSexo == id);
            if (sexo == null)
            {
                return NotFound();
            }

            return View(sexo);
        }

        // POST: Admin/Sexos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(byte id)
        {
            if (_context.Sexos == null)
            {
                return Problem("Entity set 'MiHadaMadrinaHandMadeDBContext.Sexos'  is null.");
            }
            var sexo = await _context.Sexos.FindAsync(id);
            if (sexo != null)
            {
                _context.Sexos.Remove(sexo);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SexoExists(byte id)
        {
          return (_context.Sexos?.Any(e => e.IdSexo == id)).GetValueOrDefault();
        }
    }
}

MiHadaMadrinaShop/Areas/Admin/Views/Sexos/Create.cshtml
@model MiHadaMadrinaShop.Models.Sexo

@{
    ViewData["Title"] = "Crear sexo";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="container py-5 d-flex flex-column min-vh-100">
    <div class="row">
        <div class="col mt-4">
            <h1 class="font-weight-bold font-italic">Sexo</h1>
        </div>
    </div>
    <ol class="breadcrumb mb-4 bg-transparent">
        <li><a asp-area="Admin" asp-controller="Pedidos" asp-action="Index" class="text-black-50 text-decoration-none">Dashboard</a><i class="fas fa-angle-right text-black-50 px-2"></i></li>
        <li><a asp-area="Admin" asp-controller="Sexos" asp-action="Index" class="text-black-50 text-decoration-none">Sexo</a><i class="fas fa-angle-right text-black-50 px-2"></i></li>
        <li><a asp-area="Admin" asp-controller="Sexos" asp-action="Create" class="text-dark text-decoration-none active">Crear</a></li>
    </ol>
    <hr class="d-block d-md-none" />

    <div class="row">
        <div class="col-12 col-md-6 align-items-center">
            <div class="card d-flex justify-content-center p-4">
                <div class="card-header">
                    <h1 class="font-weight-bold font-italic">Crear sexo</h1>
                </div>
                <form asp-action="Create" method="post">
                    <div class="card-body py-0">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group mb-3">
                            <label asp-for="Sexo1" class="control-label"></label>
                            <input asp-for="Sexo1" class="form-control" />
                            <span asp-validation-for="Sexo1" class="text-danger"></span>
                        </div>
                        <div class="card-footer">
                            <div class="form-group justify-content-between" role="group" aria-label="Botones">
                                <a asp-action="Index" class="btn btn-secondary w-auto mb-1"><i class="fas fa-arrow-left"></i> Volver</a>&nbsp;
                                <button type="submit" class="btn btn-primary w-auto mb-1"><i class="fas fa-save"></i> Guardar</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="col-8 col-md-4 align-items-center">
            <img src="~/img/illustrations/undraw_my_documents_re_13dc.svg" alt="imagen de creaci&oacute;n" class="imagen-width img-fluid rounded mx-auto" />
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

MiHadaMadrinaShop/Areas/Admin/Views/Sexos/Delete.cshtml
@model MiHadaMadrinaShop.Models.Sexo

@{
    ViewData["Title"] = "Eliminar sexo";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="container py-5 d-flex flex-column min-vh-100">
    <div class="row">
        <div class="col mt-4">
            <h1 class="font-weight-bold font-italic">Sexo</h1>
        </div>
    </div>
    <ol class="breadcrumb mb-4 bg-transparent">
        <li><a asp-area="Admin" asp-controller="Pedidos" asp-action="Index" class="text-black-50 text-decoration-none">Dashboard</a><i class="fas fa-angle-right text-black-50 px-2"></i></li>
        <li><a asp-area="Admin" asp-controller="Sexos" asp-action="Index" class="text-black-50 text-decoration-none">Sexo</a><i class="fas fa-angle-right text-black-50 px-2"></i></li>
        <li><a asp-area="Admin" asp-controller="Sexos" asp-action="Delete" class="text-dark text-decoration-none active">Eliminar</a></li>
    </ol>
    <hr class="d-block d-md-none" />

    <div class="row">
        <div class="col-12 col-md-6 align-items-center">
            <div class="card d-flex justify-content-center p-4">
                <div class="card-header">
                    <h1 class="font-weight-bold font-italic">Eliminar tipo de sexo</h1>
                </div>
                <form asp-action="Delete" method="post">
                    <div class="card-body py-0">
                        <h3>¿Est&aacute;s seguro de querer eliminar el tipo de sexo @Html.DisplayFor(model => model.Sexo1)?</h3>
                        <input type="hidden" asp-for="IdSexo" />
                        <div class="card-footer">
                            <div class="form-group justify-content-between" role="group" aria-label="Botones">
                                <a asp-action="Index" class="btn btn-secondary w-auto mb-1"><i class="fas fa-arrow-left"></i> Volver</a>&nbsp;
                                <button type="submit" class="btn btn-danger w-auto mb-1"><i class="fas fa-trash-alt"></i> Eliminar</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="col-8 col-md-4 align-items-center">
            <img src="~/img/illustrations/undraw_cancel_re_pkdm.svg" alt="eliminar imagen" class="imagen-width img-fluid rounded mx-auto" />
        </div>
    </div>
</div>

MiHadaMadrinaShop/Areas/Admin/Views/Sexos/Edit.cshtml
@model MiHadaMadrinaShop.Models.Sexo

@{
    ViewData["Title"] = "Editar sexo";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="container py-5 d-flex flex-column min-vh-100">
    <div class="row">
        <div class="col mt-4">
            <h1 class="font-weight-bold font-italic">Sexo</h1>
        </div>
    </div>
    <ol class="breadcrumb mb-4 bg-transparent">
        <li><a asp-area="Admin" asp-controller="Pedidos" asp-action="Index" class="text-black-50 text-decoration-none">Dashboard</a><i class="fas fa-angle-right text-black-50 px-2"></i></li>
        <li><a asp-area="Admin" asp-controller="Sexos" asp-action="Index" class="text-black-50 text-decoration-none">Sexo</a><i class="fas fa-angle-right text-black-50 px-2"></i></li>
        <li><a asp-area="Admin" asp-controller="Sexos" asp-action="Edit" class="text-dark text-decoration-none active">Editar</a></li>
    </ol>
    <hr class="d-block d-md-none" />

    <div class="row">
        <div class="col-12 col-md-6 align-items-center">
            <div class="card d-flex justify-content-center p-4">
                <div class="card-header">
                    <h1 class="font-weight-bold font-italic">Editar sexos</h1>
                </div>
                <form asp-action="Edit" method="post">
                    <div class="card-body py-0">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <input type="hidden" asp-for="IdSexo" />
                        <div class="form-group mb-3">
                            <label asp-for="Sexo1" class="control-label"></label>
                            <input asp-for="Sexo1" class="form-control" />
                            <span asp-validation-for="Sexo1" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="form-group justify-content-between" role="group" aria-label="Botones">
                            <a asp-action="Index" class="btn btn-secondary w-auto mb-1"><i class="fas fa-arrow-left"></i> Volver</a>&nbsp;
                            <button type="submit" class="btn btn-primary w-auto mb-1"><i class="fas fa-save"></i> Guardar</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="col-8 col-md-4 align-items-center">
            <img src="~/img/illustrations/undraw_my_documents_re_13dc.svg" alt="imagen de edici&oacute;n" class="imagen-width img-fluid rounded mx-auto" />
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

MiHadaMadrinaShop/Areas/Admin/Views/Sexos/Index.cshtml
@model IEnumerable<MiHadaMadrinaShop.Models.Sexo>

@{
    ViewData["Title"] = "Lista de tipos de sexo";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="container py-5 d-flex flex-column min-vh-100">
    <ol class="breadcrumb mt-4 bg-transparent">
        <li><a asp-area="Admin" asp-controller="Pedidos" asp-action="Index" class="text-black-50 text-decoration-none">Dashboard</a><i class="fas fa-angle-right text-black-50 px-2"></i></li>
        <li><a asp-area="Admin" asp-controller="Sexos" asp-action="Index" class="text-dark text-decoration-none active">Sexo</a></li>
    </ol>
    <hr class="d-block d-md-none" />
    <div class="row">
        <div class="col mt-4 d-flex justify-content-between align-items-center">
            <h1 class="font-weight-bold font-italic">Lista de tipos de sexo</h1>
            <a class="btn btn-primary" asp-action="Create">
                <i class="fas fa-plus"></i><span>&nbsp;Nuevo</span>
            </a>
        </div>
    </div>

    <div class="row">
        <div class="col-12 text-center">
            <div class="table-responsive">
                <table class="table table-hover border">
                    <thead class="thead-color">
                        <tr class="align-self-center">
                            <th class="py-3 text-center" scope="col">
                                @Html.DisplayNameFor(model => model.Sexo1)
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td class="pt-3 text-center">
                                    @Html.DisplayFor(modelItem => item.Sexo1)
                                </td>
                                <td class="pt-3 text-center">
                                    <a class="btn btn-warning mx-auto opacity-50" asp-action="Edit" asp-route-id="@item.IdSexo"><i class="fas fa-edit"></i></a>
                                    <a class="btn btn-danger mx-auto" asp-action="Delete" asp-route-id="@item.IdSexo"><i class="fas fa-trash"></i></a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>